


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing ApiErrorResponseErrors
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorResponseErrorsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiErrorResponseErrors
        //private ApiErrorResponseErrors instance;

        public ApiErrorResponseErrorsTests()
        {
            // TODO uncomment below to create an instance of ApiErrorResponseErrors
            //instance = new ApiErrorResponseErrors();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiErrorResponseErrors
        /// </summary>
        [Fact]
        public void ApiErrorResponseErrorsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiErrorResponseErrors
            //Assert.IsInstanceOfType<ApiErrorResponseErrors> (instance, "variable 'instance' is a ApiErrorResponseErrors");
        }


        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
