


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing ApiErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiErrorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiErrorResponse
        //private ApiErrorResponse instance;

        public ApiErrorResponseTests()
        {
            // TODO uncomment below to create an instance of ApiErrorResponse
            //instance = new ApiErrorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiErrorResponse
        /// </summary>
        [Fact]
        public void ApiErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApiErrorResponse
            //Assert.IsInstanceOfType<ApiErrorResponse> (instance, "variable 'instance' is a ApiErrorResponse");
        }


        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

    }

}
