


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing ApplicationStateTransitionEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationStateTransitionEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationStateTransitionEvent
        //private ApplicationStateTransitionEvent instance;

        public ApplicationStateTransitionEventTests()
        {
            // TODO uncomment below to create an instance of ApplicationStateTransitionEvent
            //instance = new ApplicationStateTransitionEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationStateTransitionEvent
        /// </summary>
        [Fact]
        public void ApplicationStateTransitionEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationStateTransitionEvent
            //Assert.IsInstanceOfType<ApplicationStateTransitionEvent> (instance, "variable 'instance' is a ApplicationStateTransitionEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
