


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ApplicationStateTransitionEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationStateTransitionEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationStateTransitionEventDataAllOf
        //private ApplicationStateTransitionEventDataAllOf instance;

        public ApplicationStateTransitionEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of ApplicationStateTransitionEventDataAllOf
            //instance = new ApplicationStateTransitionEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationStateTransitionEventDataAllOf
        /// </summary>
        [Fact]
        public void ApplicationStateTransitionEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationStateTransitionEventDataAllOf
            //Assert.IsInstanceOfType<ApplicationStateTransitionEventDataAllOf> (instance, "variable 'instance' is a ApplicationStateTransitionEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'SuccessfullyClosed'
        /// </summary>
        [Fact]
        public void SuccessfullyClosedTest()
        {
            // TODO unit test for the property 'SuccessfullyClosed'
        }
        /// <summary>
        /// Test the property 'IsFirstRun'
        /// </summary>
        [Fact]
        public void IsFirstRunTest()
        {
            // TODO unit test for the property 'IsFirstRun'
        }
        /// <summary>
        /// Test the property 'IsUpgrade'
        /// </summary>
        [Fact]
        public void IsUpgradeTest()
        {
            // TODO unit test for the property 'IsUpgrade'
        }
        /// <summary>
        /// Test the property 'PushNotificationPayload'
        /// </summary>
        [Fact]
        public void PushNotificationPayloadTest()
        {
            // TODO unit test for the property 'PushNotificationPayload'
        }
        /// <summary>
        /// Test the property 'LaunchReferral'
        /// </summary>
        [Fact]
        public void LaunchReferralTest()
        {
            // TODO unit test for the property 'LaunchReferral'
        }
        /// <summary>
        /// Test the property 'ApplicationTransitionType'
        /// </summary>
        [Fact]
        public void ApplicationTransitionTypeTest()
        {
            // TODO unit test for the property 'ApplicationTransitionType'
        }

    }

}
