


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ApplicationInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplicationInformationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplicationInformation
        //private ApplicationInformation instance;

        public ApplicationInformationTests()
        {
            // TODO uncomment below to create an instance of ApplicationInformation
            //instance = new ApplicationInformation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplicationInformation
        /// </summary>
        [Fact]
        public void ApplicationInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ApplicationInformation
            //Assert.IsInstanceOfType<ApplicationInformation> (instance, "variable 'instance' is a ApplicationInformation");
        }


        /// <summary>
        /// Test the property 'ApplicationName'
        /// </summary>
        [Fact]
        public void ApplicationNameTest()
        {
            // TODO unit test for the property 'ApplicationName'
        }
        /// <summary>
        /// Test the property 'ApplicationVersion'
        /// </summary>
        [Fact]
        public void ApplicationVersionTest()
        {
            // TODO unit test for the property 'ApplicationVersion'
        }
        /// <summary>
        /// Test the property 'ApplicationBuildNumber'
        /// </summary>
        [Fact]
        public void ApplicationBuildNumberTest()
        {
            // TODO unit test for the property 'ApplicationBuildNumber'
        }
        /// <summary>
        /// Test the property 'InstallReferrer'
        /// </summary>
        [Fact]
        public void InstallReferrerTest()
        {
            // TODO unit test for the property 'InstallReferrer'
        }
        /// <summary>
        /// Test the property 'Package'
        /// </summary>
        [Fact]
        public void PackageTest()
        {
            // TODO unit test for the property 'Package'
        }
        /// <summary>
        /// Test the property 'Os'
        /// </summary>
        [Fact]
        public void OsTest()
        {
            // TODO unit test for the property 'Os'
        }
        /// <summary>
        /// Test the property 'AppleSearchAdsAttributes'
        /// </summary>
        [Fact]
        public void AppleSearchAdsAttributesTest()
        {
            // TODO unit test for the property 'AppleSearchAdsAttributes'
        }

    }

}
