


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing AttributionInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AttributionInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AttributionInfo
        //private AttributionInfo instance;

        public AttributionInfoTests()
        {
            // TODO uncomment below to create an instance of AttributionInfo
            //instance = new AttributionInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AttributionInfo
        /// </summary>
        [Fact]
        public void AttributionInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AttributionInfo
            //Assert.IsInstanceOfType<AttributionInfo> (instance, "variable 'instance' is a AttributionInfo");
        }


        /// <summary>
        /// Test the property 'ServiceProvider'
        /// </summary>
        [Fact]
        public void ServiceProviderTest()
        {
            // TODO unit test for the property 'ServiceProvider'
        }
        /// <summary>
        /// Test the property 'Publisher'
        /// </summary>
        [Fact]
        public void PublisherTest()
        {
            // TODO unit test for the property 'Publisher'
        }
        /// <summary>
        /// Test the property 'Campaign'
        /// </summary>
        [Fact]
        public void CampaignTest()
        {
            // TODO unit test for the property 'Campaign'
        }

    }

}
