


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing Batch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Batch
        //private Batch instance;

        public BatchTests()
        {
            // TODO uncomment below to create an instance of Batch
            //instance = new Batch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Batch
        /// </summary>
        [Fact]
        public void BatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Batch
            //Assert.IsInstanceOfType<Batch> (instance, "variable 'instance' is a Batch");
        }


        /// <summary>
        /// Test the property 'SourceRequestId'
        /// </summary>
        [Fact]
        public void SourceRequestIdTest()
        {
            // TODO unit test for the property 'SourceRequestId'
        }
        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Fact]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'DeviceInfo'
        /// </summary>
        [Fact]
        public void DeviceInfoTest()
        {
            // TODO unit test for the property 'DeviceInfo'
        }
        /// <summary>
        /// Test the property 'ApplicationInfo'
        /// </summary>
        [Fact]
        public void ApplicationInfoTest()
        {
            // TODO unit test for the property 'ApplicationInfo'
        }
        /// <summary>
        /// Test the property 'UserAttributes'
        /// </summary>
        [Fact]
        public void UserAttributesTest()
        {
            // TODO unit test for the property 'UserAttributes'
        }
        /// <summary>
        /// Test the property 'DeletedUserAttributes'
        /// </summary>
        [Fact]
        public void DeletedUserAttributesTest()
        {
            // TODO unit test for the property 'DeletedUserAttributes'
        }
        /// <summary>
        /// Test the property 'UserIdentities'
        /// </summary>
        [Fact]
        public void UserIdentitiesTest()
        {
            // TODO unit test for the property 'UserIdentities'
        }
        /// <summary>
        /// Test the property 'Environment'
        /// </summary>
        [Fact]
        public void EnvironmentTest()
        {
            // TODO unit test for the property 'Environment'
        }
    
        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }
        /// <summary>
        /// Test the property 'IntegrationAttributes'
        /// </summary>
        [Fact]
        public void IntegrationAttributesTest()
        {
            // TODO unit test for the property 'IntegrationAttributes'
        }
        /// <summary>
        /// Test the property 'PartnerIdentity'
        /// </summary>
        [Fact]
        public void PartnerIdentityTest()
        {
            // TODO unit test for the property 'PartnerIdentity'
        }
        /// <summary>
        /// Test the property 'SourceInfo'
        /// </summary>
        [Fact]
        public void SourceInfoTest()
        {
            // TODO unit test for the property 'SourceInfo'
        }
        /// <summary>
        /// Test the property 'MpDeviceid'
        /// </summary>
        [Fact]
        public void MpDeviceidTest()
        {
            // TODO unit test for the property 'MpDeviceid'
        }
        /// <summary>
        /// Test the property 'AttributionInfo'
        /// </summary>
        [Fact]
        public void AttributionInfoTest()
        {
            // TODO unit test for the property 'AttributionInfo'
        }
        /// <summary>
        /// Test the property 'TimestampUnixtimeMs'
        /// </summary>
        [Fact]
        public void TimestampUnixtimeMsTest()
        {
            // TODO unit test for the property 'TimestampUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }
        /// <summary>
        /// Test the property 'Mpid'
        /// </summary>
        [Fact]
        public void MpidTest()
        {
            // TODO unit test for the property 'Mpid'
        }
        /// <summary>
        /// Test the property 'SdkVersion'
        /// </summary>
        [Fact]
        public void SdkVersionTest()
        {
            // TODO unit test for the property 'SdkVersion'
        }
        /// <summary>
        /// Test the property 'ConsentState'
        /// </summary>
        [Fact]
        public void ConsentStateTest()
        {
            // TODO unit test for the property 'ConsentState'
        }
        /// <summary>
        /// Test the property 'JobId'
        /// </summary>
        [Fact]
        public void JobIdTest()
        {
            // TODO unit test for the property 'JobId'
        }

    }

}
