


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing BatchUserIdentities
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchUserIdentitiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchUserIdentities
        //private BatchUserIdentities instance;

        public BatchUserIdentitiesTests()
        {
            // TODO uncomment below to create an instance of BatchUserIdentities
            //instance = new BatchUserIdentities();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchUserIdentities
        /// </summary>
        [Fact]
        public void BatchUserIdentitiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchUserIdentities
            //Assert.IsInstanceOfType<BatchUserIdentities> (instance, "variable 'instance' is a BatchUserIdentities");
        }


        /// <summary>
        /// Test the property 'Other'
        /// </summary>
        [Fact]
        public void OtherTest()
        {
            // TODO unit test for the property 'Other'
        }
        /// <summary>
        /// Test the property 'CustomerId'
        /// </summary>
        [Fact]
        public void CustomerIdTest()
        {
            // TODO unit test for the property 'CustomerId'
        }
        /// <summary>
        /// Test the property 'Facebook'
        /// </summary>
        [Fact]
        public void FacebookTest()
        {
            // TODO unit test for the property 'Facebook'
        }
        /// <summary>
        /// Test the property 'Twitter'
        /// </summary>
        [Fact]
        public void TwitterTest()
        {
            // TODO unit test for the property 'Twitter'
        }
        /// <summary>
        /// Test the property 'Google'
        /// </summary>
        [Fact]
        public void GoogleTest()
        {
            // TODO unit test for the property 'Google'
        }
        /// <summary>
        /// Test the property 'Microsoft'
        /// </summary>
        [Fact]
        public void MicrosoftTest()
        {
            // TODO unit test for the property 'Microsoft'
        }
        /// <summary>
        /// Test the property 'Yahoo'
        /// </summary>
        [Fact]
        public void YahooTest()
        {
            // TODO unit test for the property 'Yahoo'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Alias'
        /// </summary>
        [Fact]
        public void AliasTest()
        {
            // TODO unit test for the property 'Alias'
        }
        /// <summary>
        /// Test the property 'FacebookCustomAudienceId'
        /// </summary>
        [Fact]
        public void FacebookCustomAudienceIdTest()
        {
            // TODO unit test for the property 'FacebookCustomAudienceId'
        }
        /// <summary>
        /// Test the property 'OtherId2'
        /// </summary>
        [Fact]
        public void OtherId2Test()
        {
            // TODO unit test for the property 'OtherId2'
        }
        /// <summary>
        /// Test the property 'OtherId3'
        /// </summary>
        [Fact]
        public void OtherId3Test()
        {
            // TODO unit test for the property 'OtherId3'
        }
        /// <summary>
        /// Test the property 'OtherId4'
        /// </summary>
        [Fact]
        public void OtherId4Test()
        {
            // TODO unit test for the property 'OtherId4'
        }
        /// <summary>
        /// Test the property 'OtherId5'
        /// </summary>
        [Fact]
        public void OtherId5Test()
        {
            // TODO unit test for the property 'OtherId5'
        }
        /// <summary>
        /// Test the property 'OtherId6'
        /// </summary>
        [Fact]
        public void OtherId6Test()
        {
            // TODO unit test for the property 'OtherId6'
        }
        /// <summary>
        /// Test the property 'OtherId7'
        /// </summary>
        [Fact]
        public void OtherId7Test()
        {
            // TODO unit test for the property 'OtherId7'
        }
        /// <summary>
        /// Test the property 'OtherId8'
        /// </summary>
        [Fact]
        public void OtherId8Test()
        {
            // TODO unit test for the property 'OtherId8'
        }
        /// <summary>
        /// Test the property 'OtherId9'
        /// </summary>
        [Fact]
        public void OtherId9Test()
        {
            // TODO unit test for the property 'OtherId9'
        }
        /// <summary>
        /// Test the property 'OtherId10'
        /// </summary>
        [Fact]
        public void OtherId10Test()
        {
            // TODO unit test for the property 'OtherId10'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Fact]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'PhoneNumber2'
        /// </summary>
        [Fact]
        public void PhoneNumber2Test()
        {
            // TODO unit test for the property 'PhoneNumber2'
        }
        /// <summary>
        /// Test the property 'PhoneNumber3'
        /// </summary>
        [Fact]
        public void PhoneNumber3Test()
        {
            // TODO unit test for the property 'PhoneNumber3'
        }

    }

}
