


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing BatchContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchContext
        //private BatchContext instance;

        public BatchContextTests()
        {
            // TODO uncomment below to create an instance of BatchContext
            //instance = new BatchContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchContext
        /// </summary>
        [Fact]
        public void BatchContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchContext
            //Assert.IsInstanceOfType<BatchContext> (instance, "variable 'instance' is a BatchContext");
        }


        /// <summary>
        /// Test the property 'DataPlan'
        /// </summary>
        [Fact]
        public void DataPlanTest()
        {
            // TODO unit test for the property 'DataPlan'
        }

    }

}
