


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing BreadcrumbEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BreadcrumbEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BreadcrumbEvent
        //private BreadcrumbEvent instance;

        public BreadcrumbEventTests()
        {
            // TODO uncomment below to create an instance of BreadcrumbEvent
            //instance = new BreadcrumbEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BreadcrumbEvent
        /// </summary>
        [Fact]
        public void BreadcrumbEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BreadcrumbEvent
            //Assert.IsInstanceOfType<BreadcrumbEvent> (instance, "variable 'instance' is a BreadcrumbEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
