


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing BreadcrumbEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BreadcrumbEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BreadcrumbEventDataAllOf
        //private BreadcrumbEventDataAllOf instance;

        public BreadcrumbEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of BreadcrumbEventDataAllOf
            //instance = new BreadcrumbEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BreadcrumbEventDataAllOf
        /// </summary>
        [Fact]
        public void BreadcrumbEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BreadcrumbEventDataAllOf
            //Assert.IsInstanceOfType<BreadcrumbEventDataAllOf> (instance, "variable 'instance' is a BreadcrumbEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'SessionNumber'
        /// </summary>
        [Fact]
        public void SessionNumberTest()
        {
            // TODO unit test for the property 'SessionNumber'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

    }

}
