


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing CommerceEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommerceEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommerceEvent
        //private CommerceEvent instance;

        public CommerceEventTests()
        {
            // TODO uncomment below to create an instance of CommerceEvent
            //instance = new CommerceEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommerceEvent
        /// </summary>
        [Fact]
        public void CommerceEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommerceEvent
            //Assert.IsInstanceOfType<CommerceEvent> (instance, "variable 'instance' is a CommerceEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
