


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing CommerceEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommerceEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommerceEventDataAllOf
        //private CommerceEventDataAllOf instance;

        public CommerceEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of CommerceEventDataAllOf
            //instance = new CommerceEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommerceEventDataAllOf
        /// </summary>
        [Fact]
        public void CommerceEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CommerceEventDataAllOf
            //Assert.IsInstanceOfType<CommerceEventDataAllOf> (instance, "variable 'instance' is a CommerceEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'ProductAction'
        /// </summary>
        [Fact]
        public void ProductActionTest()
        {
            // TODO unit test for the property 'ProductAction'
        }
        /// <summary>
        /// Test the property 'PromotionAction'
        /// </summary>
        [Fact]
        public void PromotionActionTest()
        {
            // TODO unit test for the property 'PromotionAction'
        }
        /// <summary>
        /// Test the property 'ProductImpressions'
        /// </summary>
        [Fact]
        public void ProductImpressionsTest()
        {
            // TODO unit test for the property 'ProductImpressions'
        }
        /// <summary>
        /// Test the property 'ShoppingCart'
        /// </summary>
        [Fact]
        public void ShoppingCartTest()
        {
            // TODO unit test for the property 'ShoppingCart'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'ScreenName'
        /// </summary>
        [Fact]
        public void ScreenNameTest()
        {
            // TODO unit test for the property 'ScreenName'
        }
        /// <summary>
        /// Test the property 'IsNonInteractive'
        /// </summary>
        [Fact]
        public void IsNonInteractiveTest()
        {
            // TODO unit test for the property 'IsNonInteractive'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Fact]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'CustomEventType'
        /// </summary>
        [Fact]
        public void CustomEventTypeTest()
        {
            // TODO unit test for the property 'CustomEventType'
        }
        /// <summary>
        /// Test the property 'CustomFlags'
        /// </summary>
        [Fact]
        public void CustomFlagsTest()
        {
            // TODO unit test for the property 'CustomFlags'
        }

    }

}
