


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ConsentState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsentStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsentState
        //private ConsentState instance;

        public ConsentStateTests()
        {
            // TODO uncomment below to create an instance of ConsentState
            //instance = new ConsentState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsentState
        /// </summary>
        [Fact]
        public void ConsentStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConsentState
            //Assert.IsInstanceOfType<ConsentState> (instance, "variable 'instance' is a ConsentState");
        }


        /// <summary>
        /// Test the property 'Gdpr'
        /// </summary>
        [Fact]
        public void GdprTest()
        {
            // TODO unit test for the property 'Gdpr'
        }

    }

}
