


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing CrashReportEventData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CrashReportEventDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CrashReportEventData
        //private CrashReportEventData instance;

        public CrashReportEventDataTests()
        {
            // TODO uncomment below to create an instance of CrashReportEventData
            //instance = new CrashReportEventData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CrashReportEventData
        /// </summary>
        [Fact]
        public void CrashReportEventDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CrashReportEventData
            //Assert.IsInstanceOfType<CrashReportEventData> (instance, "variable 'instance' is a CrashReportEventData");
        }


        /// <summary>
        /// Test the property 'TimestampUnixtimeMs'
        /// </summary>
        [Fact]
        public void TimestampUnixtimeMsTest()
        {
            // TODO unit test for the property 'TimestampUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Fact]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'SourceMessageId'
        /// </summary>
        [Fact]
        public void SourceMessageIdTest()
        {
            // TODO unit test for the property 'SourceMessageId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'SessionUuid'
        /// </summary>
        [Fact]
        public void SessionUuidTest()
        {
            // TODO unit test for the property 'SessionUuid'
        }
        /// <summary>
        /// Test the property 'SessionStartUnixtimeMs'
        /// </summary>
        [Fact]
        public void SessionStartUnixtimeMsTest()
        {
            // TODO unit test for the property 'SessionStartUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'EventStartUnixtimeMs'
        /// </summary>
        [Fact]
        public void EventStartUnixtimeMsTest()
        {
            // TODO unit test for the property 'EventStartUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Fact]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'DeviceCurrentState'
        /// </summary>
        [Fact]
        public void DeviceCurrentStateTest()
        {
            // TODO unit test for the property 'DeviceCurrentState'
        }
        /// <summary>
        /// Test the property 'IsGoalDefined'
        /// </summary>
        [Fact]
        public void IsGoalDefinedTest()
        {
            // TODO unit test for the property 'IsGoalDefined'
        }
        /// <summary>
        /// Test the property 'LifetimeValueChange'
        /// </summary>
        [Fact]
        public void LifetimeValueChangeTest()
        {
            // TODO unit test for the property 'LifetimeValueChange'
        }
        /// <summary>
        /// Test the property 'LifetimeValueAttributeName'
        /// </summary>
        [Fact]
        public void LifetimeValueAttributeNameTest()
        {
            // TODO unit test for the property 'LifetimeValueAttributeName'
        }
        /// <summary>
        /// Test the property 'DataConnectionType'
        /// </summary>
        [Fact]
        public void DataConnectionTypeTest()
        {
            // TODO unit test for the property 'DataConnectionType'
        }
        /// <summary>
        /// Test the property 'EventNum'
        /// </summary>
        [Fact]
        public void EventNumTest()
        {
            // TODO unit test for the property 'EventNum'
        }
        /// <summary>
        /// Test the property 'ViewController'
        /// </summary>
        [Fact]
        public void ViewControllerTest()
        {
            // TODO unit test for the property 'ViewController'
        }
        /// <summary>
        /// Test the property 'IsMainThread'
        /// </summary>
        [Fact]
        public void IsMainThreadTest()
        {
            // TODO unit test for the property 'IsMainThread'
        }
        /// <summary>
        /// Test the property 'CanonicalName'
        /// </summary>
        [Fact]
        public void CanonicalNameTest()
        {
            // TODO unit test for the property 'CanonicalName'
        }
        /// <summary>
        /// Test the property 'EventSystemNotificationInfo'
        /// </summary>
        [Fact]
        public void EventSystemNotificationInfoTest()
        {
            // TODO unit test for the property 'EventSystemNotificationInfo'
        }
        /// <summary>
        /// Test the property 'Breadcrumbs'
        /// </summary>
        [Fact]
        public void BreadcrumbsTest()
        {
            // TODO unit test for the property 'Breadcrumbs'
        }
        /// <summary>
        /// Test the property 'ClassName'
        /// </summary>
        [Fact]
        public void ClassNameTest()
        {
            // TODO unit test for the property 'ClassName'
        }
        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'StackTrace'
        /// </summary>
        [Fact]
        public void StackTraceTest()
        {
            // TODO unit test for the property 'StackTrace'
        }
        /// <summary>
        /// Test the property 'ExceptionHandled'
        /// </summary>
        [Fact]
        public void ExceptionHandledTest()
        {
            // TODO unit test for the property 'ExceptionHandled'
        }
        /// <summary>
        /// Test the property 'TopmostContext'
        /// </summary>
        [Fact]
        public void TopmostContextTest()
        {
            // TODO unit test for the property 'TopmostContext'
        }
        /// <summary>
        /// Test the property 'PlCrashReportFileBase64'
        /// </summary>
        [Fact]
        public void PlCrashReportFileBase64Test()
        {
            // TODO unit test for the property 'PlCrashReportFileBase64'
        }
        /// <summary>
        /// Test the property 'IosImageBaseAddress'
        /// </summary>
        [Fact]
        public void IosImageBaseAddressTest()
        {
            // TODO unit test for the property 'IosImageBaseAddress'
        }
        /// <summary>
        /// Test the property 'IosImageSize'
        /// </summary>
        [Fact]
        public void IosImageSizeTest()
        {
            // TODO unit test for the property 'IosImageSize'
        }
        /// <summary>
        /// Test the property 'SessionNumber'
        /// </summary>
        [Fact]
        public void SessionNumberTest()
        {
            // TODO unit test for the property 'SessionNumber'
        }

    }

}
