


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing CustomEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomEventDataAllOf
        //private CustomEventDataAllOf instance;

        public CustomEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of CustomEventDataAllOf
            //instance = new CustomEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomEventDataAllOf
        /// </summary>
        [Fact]
        public void CustomEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomEventDataAllOf
            //Assert.IsInstanceOfType<CustomEventDataAllOf> (instance, "variable 'instance' is a CustomEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'CustomEventType'
        /// </summary>
        [Fact]
        public void CustomEventTypeTest()
        {
            // TODO unit test for the property 'CustomEventType'
        }
        /// <summary>
        /// Test the property 'EventName'
        /// </summary>
        [Fact]
        public void EventNameTest()
        {
            // TODO unit test for the property 'EventName'
        }
        /// <summary>
        /// Test the property 'CustomFlags'
        /// </summary>
        [Fact]
        public void CustomFlagsTest()
        {
            // TODO unit test for the property 'CustomFlags'
        }

    }

}
