


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing CustomEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomEvent
        //private CustomEvent instance;

        public CustomEventTests()
        {
            // TODO uncomment below to create an instance of CustomEvent
            //instance = new CustomEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomEvent
        /// </summary>
        [Fact]
        public void CustomEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomEvent
            //Assert.IsInstanceOfType<CustomEvent> (instance, "variable 'instance' is a CustomEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
