


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing DataPlanContext
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataPlanContextTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataPlanContext
        //private DataPlanContext instance;

        public DataPlanContextTests()
        {
            // TODO uncomment below to create an instance of DataPlanContext
            //instance = new DataPlanContext();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataPlanContext
        /// </summary>
        [Fact]
        public void DataPlanContextInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DataPlanContext
            //Assert.IsInstanceOfType<DataPlanContext> (instance, "variable 'instance' is a DataPlanContext");
        }


        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Fact]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'PlanVersion'
        /// </summary>
        [Fact]
        public void PlanVersionTest()
        {
            // TODO unit test for the property 'PlanVersion'
        }

    }

}
