


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing DeviceCurrentState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceCurrentStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceCurrentState
        //private DeviceCurrentState instance;

        public DeviceCurrentStateTests()
        {
            // TODO uncomment below to create an instance of DeviceCurrentState
            //instance = new DeviceCurrentState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceCurrentState
        /// </summary>
        [Fact]
        public void DeviceCurrentStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeviceCurrentState
            //Assert.IsInstanceOfType<DeviceCurrentState> (instance, "variable 'instance' is a DeviceCurrentState");
        }


        /// <summary>
        /// Test the property 'TimeSinceStartMs'
        /// </summary>
        [Fact]
        public void TimeSinceStartMsTest()
        {
            // TODO unit test for the property 'TimeSinceStartMs'
        }
        /// <summary>
        /// Test the property 'BatteryLevel'
        /// </summary>
        [Fact]
        public void BatteryLevelTest()
        {
            // TODO unit test for the property 'BatteryLevel'
        }
        /// <summary>
        /// Test the property 'DataConnectionType'
        /// </summary>
        [Fact]
        public void DataConnectionTypeTest()
        {
            // TODO unit test for the property 'DataConnectionType'
        }
        /// <summary>
        /// Test the property 'DataConnectionTypeDetail'
        /// </summary>
        [Fact]
        public void DataConnectionTypeDetailTest()
        {
            // TODO unit test for the property 'DataConnectionTypeDetail'
        }
        /// <summary>
        /// Test the property 'GpsState'
        /// </summary>
        [Fact]
        public void GpsStateTest()
        {
            // TODO unit test for the property 'GpsState'
        }
        /// <summary>
        /// Test the property 'TotalSystemMemoryUsageBytes'
        /// </summary>
        [Fact]
        public void TotalSystemMemoryUsageBytesTest()
        {
            // TODO unit test for the property 'TotalSystemMemoryUsageBytes'
        }
        /// <summary>
        /// Test the property 'DiskSpaceFreeBytes'
        /// </summary>
        [Fact]
        public void DiskSpaceFreeBytesTest()
        {
            // TODO unit test for the property 'DiskSpaceFreeBytes'
        }
        /// <summary>
        /// Test the property 'ExternalDiskSpaceFreeBytes'
        /// </summary>
        [Fact]
        public void ExternalDiskSpaceFreeBytesTest()
        {
            // TODO unit test for the property 'ExternalDiskSpaceFreeBytes'
        }
        /// <summary>
        /// Test the property 'Cpu'
        /// </summary>
        [Fact]
        public void CpuTest()
        {
            // TODO unit test for the property 'Cpu'
        }
        /// <summary>
        /// Test the property 'SystemMemoryAvailableBytes'
        /// </summary>
        [Fact]
        public void SystemMemoryAvailableBytesTest()
        {
            // TODO unit test for the property 'SystemMemoryAvailableBytes'
        }
        /// <summary>
        /// Test the property 'SystemMemoryLow'
        /// </summary>
        [Fact]
        public void SystemMemoryLowTest()
        {
            // TODO unit test for the property 'SystemMemoryLow'
        }
        /// <summary>
        /// Test the property 'SystemMemoryThresholdBytes'
        /// </summary>
        [Fact]
        public void SystemMemoryThresholdBytesTest()
        {
            // TODO unit test for the property 'SystemMemoryThresholdBytes'
        }
        /// <summary>
        /// Test the property 'ApplicationMemoryAvailableBytes'
        /// </summary>
        [Fact]
        public void ApplicationMemoryAvailableBytesTest()
        {
            // TODO unit test for the property 'ApplicationMemoryAvailableBytes'
        }
        /// <summary>
        /// Test the property 'ApplicationMemoryMaxBytes'
        /// </summary>
        [Fact]
        public void ApplicationMemoryMaxBytesTest()
        {
            // TODO unit test for the property 'ApplicationMemoryMaxBytes'
        }
        /// <summary>
        /// Test the property 'ApplicationMemoryTotalBytes'
        /// </summary>
        [Fact]
        public void ApplicationMemoryTotalBytesTest()
        {
            // TODO unit test for the property 'ApplicationMemoryTotalBytes'
        }
        /// <summary>
        /// Test the property 'DeviceOrientation'
        /// </summary>
        [Fact]
        public void DeviceOrientationTest()
        {
            // TODO unit test for the property 'DeviceOrientation'
        }
        /// <summary>
        /// Test the property 'StatusBarOrientation'
        /// </summary>
        [Fact]
        public void StatusBarOrientationTest()
        {
            // TODO unit test for the property 'StatusBarOrientation'
        }

    }

}
