


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing EventType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventType
        //private EventType instance;

        public EventTypeTests()
        {
            // TODO uncomment below to create an instance of EventType
            //instance = new EventType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventType
        /// </summary>
        [Fact]
        public void EventTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventType
            //Assert.IsInstanceOfType<EventType> (instance, "variable 'instance' is a EventType");
        }



    }

}
