


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing EventSystemNotificationInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventSystemNotificationInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EventSystemNotificationInfo
        //private EventSystemNotificationInfo instance;

        public EventSystemNotificationInfoTests()
        {
            // TODO uncomment below to create an instance of EventSystemNotificationInfo
            //instance = new EventSystemNotificationInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventSystemNotificationInfo
        /// </summary>
        [Fact]
        public void EventSystemNotificationInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventSystemNotificationInfo
            //Assert.IsInstanceOfType<EventSystemNotificationInfo> (instance, "variable 'instance' is a EventSystemNotificationInfo");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
