


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing GDPRConsentState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GDPRConsentStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GDPRConsentState
        //private GDPRConsentState instance;

        public GDPRConsentStateTests()
        {
            // TODO uncomment below to create an instance of GDPRConsentState
            //instance = new GDPRConsentState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GDPRConsentState
        /// </summary>
        [Fact]
        public void GDPRConsentStateInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GDPRConsentState
            //Assert.IsInstanceOfType<GDPRConsentState> (instance, "variable 'instance' is a GDPRConsentState");
        }


        /// <summary>
        /// Test the property 'Regulation'
        /// </summary>
        [Fact]
        public void RegulationTest()
        {
            // TODO unit test for the property 'Regulation'
        }
        /// <summary>
        /// Test the property 'Document'
        /// </summary>
        [Fact]
        public void DocumentTest()
        {
            // TODO unit test for the property 'Document'
        }
        /// <summary>
        /// Test the property 'Consented'
        /// </summary>
        [Fact]
        public void ConsentedTest()
        {
            // TODO unit test for the property 'Consented'
        }
        /// <summary>
        /// Test the property 'TimestampUnixtimeMs'
        /// </summary>
        [Fact]
        public void TimestampUnixtimeMsTest()
        {
            // TODO unit test for the property 'TimestampUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'HardwareId'
        /// </summary>
        [Fact]
        public void HardwareIdTest()
        {
            // TODO unit test for the property 'HardwareId'
        }

    }

}
