


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing GeoLocation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeoLocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeoLocation
        //private GeoLocation instance;

        public GeoLocationTests()
        {
            // TODO uncomment below to create an instance of GeoLocation
            //instance = new GeoLocation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeoLocation
        /// </summary>
        [Fact]
        public void GeoLocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeoLocation
            //Assert.IsInstanceOfType<GeoLocation> (instance, "variable 'instance' is a GeoLocation");
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }
        /// <summary>
        /// Test the property 'Accuracy'
        /// </summary>
        [Fact]
        public void AccuracyTest()
        {
            // TODO unit test for the property 'Accuracy'
        }

    }

}
