


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing IdentityType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityType
        //private IdentityType instance;

        public IdentityTypeTests()
        {
            // TODO uncomment below to create an instance of IdentityType
            //instance = new IdentityType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityType
        /// </summary>
        [Fact]
        public void IdentityTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" IdentityType
            //Assert.IsInstanceOfType<IdentityType> (instance, "variable 'instance' is a IdentityType");
        }



    }

}
