


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing NetworkPerformanceEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkPerformanceEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkPerformanceEventDataAllOf
        //private NetworkPerformanceEventDataAllOf instance;

        public NetworkPerformanceEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of NetworkPerformanceEventDataAllOf
            //instance = new NetworkPerformanceEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkPerformanceEventDataAllOf
        /// </summary>
        [Fact]
        public void NetworkPerformanceEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkPerformanceEventDataAllOf
            //Assert.IsInstanceOfType<NetworkPerformanceEventDataAllOf> (instance, "variable 'instance' is a NetworkPerformanceEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'HttpVerb'
        /// </summary>
        [Fact]
        public void HttpVerbTest()
        {
            // TODO unit test for the property 'HttpVerb'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'TimeElapsed'
        /// </summary>
        [Fact]
        public void TimeElapsedTest()
        {
            // TODO unit test for the property 'TimeElapsed'
        }
        /// <summary>
        /// Test the property 'BytesIn'
        /// </summary>
        [Fact]
        public void BytesInTest()
        {
            // TODO unit test for the property 'BytesIn'
        }
        /// <summary>
        /// Test the property 'BytesOut'
        /// </summary>
        [Fact]
        public void BytesOutTest()
        {
            // TODO unit test for the property 'BytesOut'
        }
        /// <summary>
        /// Test the property 'ResponseCode'
        /// </summary>
        [Fact]
        public void ResponseCodeTest()
        {
            // TODO unit test for the property 'ResponseCode'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
