


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing NetworkPerformanceEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NetworkPerformanceEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NetworkPerformanceEvent
        //private NetworkPerformanceEvent instance;

        public NetworkPerformanceEventTests()
        {
            // TODO uncomment below to create an instance of NetworkPerformanceEvent
            //instance = new NetworkPerformanceEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NetworkPerformanceEvent
        /// </summary>
        [Fact]
        public void NetworkPerformanceEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NetworkPerformanceEvent
            //Assert.IsInstanceOfType<NetworkPerformanceEvent> (instance, "variable 'instance' is a NetworkPerformanceEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
