


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing OptOutEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptOutEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptOutEventDataAllOf
        //private OptOutEventDataAllOf instance;

        public OptOutEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of OptOutEventDataAllOf
            //instance = new OptOutEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptOutEventDataAllOf
        /// </summary>
        [Fact]
        public void OptOutEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptOutEventDataAllOf
            //Assert.IsInstanceOfType<OptOutEventDataAllOf> (instance, "variable 'instance' is a OptOutEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'IsOptedOut'
        /// </summary>
        [Fact]
        public void IsOptedOutTest()
        {
            // TODO unit test for the property 'IsOptedOut'
        }

    }

}
