


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing OptOutEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OptOutEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OptOutEvent
        //private OptOutEvent instance;

        public OptOutEventTests()
        {
            // TODO uncomment below to create an instance of OptOutEvent
            //instance = new OptOutEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OptOutEvent
        /// </summary>
        [Fact]
        public void OptOutEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OptOutEvent
            //Assert.IsInstanceOfType<OptOutEvent> (instance, "variable 'instance' is a OptOutEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
