


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing ProductImpression
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductImpressionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductImpression
        //private ProductImpression instance;

        public ProductImpressionTests()
        {
            // TODO uncomment below to create an instance of ProductImpression
            //instance = new ProductImpression();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductImpression
        /// </summary>
        [Fact]
        public void ProductImpressionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductImpression
            //Assert.IsInstanceOfType<ProductImpression> (instance, "variable 'instance' is a ProductImpression");
        }


        /// <summary>
        /// Test the property 'ProductImpressionList'
        /// </summary>
        [Fact]
        public void ProductImpressionListTest()
        {
            // TODO unit test for the property 'ProductImpressionList'
        }
        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

    }

}
