


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ProductAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductAction
        //private ProductAction instance;

        public ProductActionTests()
        {
            // TODO uncomment below to create an instance of ProductAction
            //instance = new ProductAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductAction
        /// </summary>
        [Fact]
        public void ProductActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProductAction
            //Assert.IsInstanceOfType<ProductAction> (instance, "variable 'instance' is a ProductAction");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'CheckoutStep'
        /// </summary>
        [Fact]
        public void CheckoutStepTest()
        {
            // TODO unit test for the property 'CheckoutStep'
        }
        /// <summary>
        /// Test the property 'CheckoutOptions'
        /// </summary>
        [Fact]
        public void CheckoutOptionsTest()
        {
            // TODO unit test for the property 'CheckoutOptions'
        }
        /// <summary>
        /// Test the property 'ProductActionList'
        /// </summary>
        [Fact]
        public void ProductActionListTest()
        {
            // TODO unit test for the property 'ProductActionList'
        }
        /// <summary>
        /// Test the property 'ProductListSource'
        /// </summary>
        [Fact]
        public void ProductListSourceTest()
        {
            // TODO unit test for the property 'ProductListSource'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'Affiliation'
        /// </summary>
        [Fact]
        public void AffiliationTest()
        {
            // TODO unit test for the property 'Affiliation'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Fact]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }
        /// <summary>
        /// Test the property 'ShippingAmount'
        /// </summary>
        [Fact]
        public void ShippingAmountTest()
        {
            // TODO unit test for the property 'ShippingAmount'
        }
        /// <summary>
        /// Test the property 'CouponCode'
        /// </summary>
        [Fact]
        public void CouponCodeTest()
        {
            // TODO unit test for the property 'CouponCode'
        }
        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

    }

}
