


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ProfileEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileEvent
        //private ProfileEvent instance;

        public ProfileEventTests()
        {
            // TODO uncomment below to create an instance of ProfileEvent
            //instance = new ProfileEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileEvent
        /// </summary>
        [Fact]
        public void ProfileEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProfileEvent
            //Assert.IsInstanceOfType<ProfileEvent> (instance, "variable 'instance' is a ProfileEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
