


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ProfileEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileEventDataAllOf
        //private ProfileEventDataAllOf instance;

        public ProfileEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of ProfileEventDataAllOf
            //instance = new ProfileEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileEventDataAllOf
        /// </summary>
        [Fact]
        public void ProfileEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProfileEventDataAllOf
            //Assert.IsInstanceOfType<ProfileEventDataAllOf> (instance, "variable 'instance' is a ProfileEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'PreviousMpid'
        /// </summary>
        [Fact]
        public void PreviousMpidTest()
        {
            // TODO unit test for the property 'PreviousMpid'
        }
        /// <summary>
        /// Test the property 'CurrentMpid'
        /// </summary>
        [Fact]
        public void CurrentMpidTest()
        {
            // TODO unit test for the property 'CurrentMpid'
        }
        /// <summary>
        /// Test the property 'ProfileEventType'
        /// </summary>
        [Fact]
        public void ProfileEventTypeTest()
        {
            // TODO unit test for the property 'ProfileEventType'
        }

    }

}
