


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing Promotion
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PromotionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Promotion
        //private Promotion instance;

        public PromotionTests()
        {
            // TODO uncomment below to create an instance of Promotion
            //instance = new Promotion();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Promotion
        /// </summary>
        [Fact]
        public void PromotionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Promotion
            //Assert.IsInstanceOfType<Promotion> (instance, "variable 'instance' is a Promotion");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Creative'
        /// </summary>
        [Fact]
        public void CreativeTest()
        {
            // TODO unit test for the property 'Creative'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Fact]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }

    }

}
