


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing PromotionAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PromotionActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PromotionAction
        //private PromotionAction instance;

        public PromotionActionTests()
        {
            // TODO uncomment below to create an instance of PromotionAction
            //instance = new PromotionAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PromotionAction
        /// </summary>
        [Fact]
        public void PromotionActionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PromotionAction
            //Assert.IsInstanceOfType<PromotionAction> (instance, "variable 'instance' is a PromotionAction");
        }


        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }
        /// <summary>
        /// Test the property 'Promotions'
        /// </summary>
        [Fact]
        public void PromotionsTest()
        {
            // TODO unit test for the property 'Promotions'
        }

    }

}
