


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing PushMessageEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushMessageEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushMessageEventDataAllOf
        //private PushMessageEventDataAllOf instance;

        public PushMessageEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of PushMessageEventDataAllOf
            //instance = new PushMessageEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushMessageEventDataAllOf
        /// </summary>
        [Fact]
        public void PushMessageEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PushMessageEventDataAllOf
            //Assert.IsInstanceOfType<PushMessageEventDataAllOf> (instance, "variable 'instance' is a PushMessageEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'PushMessageToken'
        /// </summary>
        [Fact]
        public void PushMessageTokenTest()
        {
            // TODO unit test for the property 'PushMessageToken'
        }
        /// <summary>
        /// Test the property 'PushMessageType'
        /// </summary>
        [Fact]
        public void PushMessageTypeTest()
        {
            // TODO unit test for the property 'PushMessageType'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }
        /// <summary>
        /// Test the property 'PushNotificationPayload'
        /// </summary>
        [Fact]
        public void PushNotificationPayloadTest()
        {
            // TODO unit test for the property 'PushNotificationPayload'
        }
        /// <summary>
        /// Test the property 'ApplicationState'
        /// </summary>
        [Fact]
        public void ApplicationStateTest()
        {
            // TODO unit test for the property 'ApplicationState'
        }
        /// <summary>
        /// Test the property 'ActionIdentifier'
        /// </summary>
        [Fact]
        public void ActionIdentifierTest()
        {
            // TODO unit test for the property 'ActionIdentifier'
        }
        /// <summary>
        /// Test the property 'PushMessageBehavior'
        /// </summary>
        [Fact]
        public void PushMessageBehaviorTest()
        {
            // TODO unit test for the property 'PushMessageBehavior'
        }

    }

}
