


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing PushRegistrationEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushRegistrationEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushRegistrationEvent
        //private PushRegistrationEvent instance;

        public PushRegistrationEventTests()
        {
            // TODO uncomment below to create an instance of PushRegistrationEvent
            //instance = new PushRegistrationEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushRegistrationEvent
        /// </summary>
        [Fact]
        public void PushRegistrationEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PushRegistrationEvent
            //Assert.IsInstanceOfType<PushRegistrationEvent> (instance, "variable 'instance' is a PushRegistrationEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
