


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing PushRegistrationEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushRegistrationEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushRegistrationEventDataAllOf
        //private PushRegistrationEventDataAllOf instance;

        public PushRegistrationEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of PushRegistrationEventDataAllOf
            //instance = new PushRegistrationEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushRegistrationEventDataAllOf
        /// </summary>
        [Fact]
        public void PushRegistrationEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PushRegistrationEventDataAllOf
            //Assert.IsInstanceOfType<PushRegistrationEventDataAllOf> (instance, "variable 'instance' is a PushRegistrationEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'Register'
        /// </summary>
        [Fact]
        public void RegisterTest()
        {
            // TODO unit test for the property 'Register'
        }
        /// <summary>
        /// Test the property 'RegistrationToken'
        /// </summary>
        [Fact]
        public void RegistrationTokenTest()
        {
            // TODO unit test for the property 'RegistrationToken'
        }

    }

}
