


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing PushMessageEventData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PushMessageEventDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PushMessageEventData
        //private PushMessageEventData instance;

        public PushMessageEventDataTests()
        {
            // TODO uncomment below to create an instance of PushMessageEventData
            //instance = new PushMessageEventData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PushMessageEventData
        /// </summary>
        [Fact]
        public void PushMessageEventDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PushMessageEventData
            //Assert.IsInstanceOfType<PushMessageEventData> (instance, "variable 'instance' is a PushMessageEventData");
        }


        /// <summary>
        /// Test the property 'TimestampUnixtimeMs'
        /// </summary>
        [Fact]
        public void TimestampUnixtimeMsTest()
        {
            // TODO unit test for the property 'TimestampUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'EventId'
        /// </summary>
        [Fact]
        public void EventIdTest()
        {
            // TODO unit test for the property 'EventId'
        }
        /// <summary>
        /// Test the property 'SourceMessageId'
        /// </summary>
        [Fact]
        public void SourceMessageIdTest()
        {
            // TODO unit test for the property 'SourceMessageId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'SessionUuid'
        /// </summary>
        [Fact]
        public void SessionUuidTest()
        {
            // TODO unit test for the property 'SessionUuid'
        }
        /// <summary>
        /// Test the property 'SessionStartUnixtimeMs'
        /// </summary>
        [Fact]
        public void SessionStartUnixtimeMsTest()
        {
            // TODO unit test for the property 'SessionStartUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'EventStartUnixtimeMs'
        /// </summary>
        [Fact]
        public void EventStartUnixtimeMsTest()
        {
            // TODO unit test for the property 'EventStartUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'CustomAttributes'
        /// </summary>
        [Fact]
        public void CustomAttributesTest()
        {
            // TODO unit test for the property 'CustomAttributes'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'DeviceCurrentState'
        /// </summary>
        [Fact]
        public void DeviceCurrentStateTest()
        {
            // TODO unit test for the property 'DeviceCurrentState'
        }
        /// <summary>
        /// Test the property 'IsGoalDefined'
        /// </summary>
        [Fact]
        public void IsGoalDefinedTest()
        {
            // TODO unit test for the property 'IsGoalDefined'
        }
        /// <summary>
        /// Test the property 'LifetimeValueChange'
        /// </summary>
        [Fact]
        public void LifetimeValueChangeTest()
        {
            // TODO unit test for the property 'LifetimeValueChange'
        }
        /// <summary>
        /// Test the property 'LifetimeValueAttributeName'
        /// </summary>
        [Fact]
        public void LifetimeValueAttributeNameTest()
        {
            // TODO unit test for the property 'LifetimeValueAttributeName'
        }
        /// <summary>
        /// Test the property 'DataConnectionType'
        /// </summary>
        [Fact]
        public void DataConnectionTypeTest()
        {
            // TODO unit test for the property 'DataConnectionType'
        }
        /// <summary>
        /// Test the property 'EventNum'
        /// </summary>
        [Fact]
        public void EventNumTest()
        {
            // TODO unit test for the property 'EventNum'
        }
        /// <summary>
        /// Test the property 'ViewController'
        /// </summary>
        [Fact]
        public void ViewControllerTest()
        {
            // TODO unit test for the property 'ViewController'
        }
        /// <summary>
        /// Test the property 'IsMainThread'
        /// </summary>
        [Fact]
        public void IsMainThreadTest()
        {
            // TODO unit test for the property 'IsMainThread'
        }
        /// <summary>
        /// Test the property 'CanonicalName'
        /// </summary>
        [Fact]
        public void CanonicalNameTest()
        {
            // TODO unit test for the property 'CanonicalName'
        }
        /// <summary>
        /// Test the property 'EventSystemNotificationInfo'
        /// </summary>
        [Fact]
        public void EventSystemNotificationInfoTest()
        {
            // TODO unit test for the property 'EventSystemNotificationInfo'
        }
        /// <summary>
        /// Test the property 'PushMessageToken'
        /// </summary>
        [Fact]
        public void PushMessageTokenTest()
        {
            // TODO unit test for the property 'PushMessageToken'
        }
        /// <summary>
        /// Test the property 'PushMessageType'
        /// </summary>
        [Fact]
        public void PushMessageTypeTest()
        {
            // TODO unit test for the property 'PushMessageType'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }
        /// <summary>
        /// Test the property 'PushNotificationPayload'
        /// </summary>
        [Fact]
        public void PushNotificationPayloadTest()
        {
            // TODO unit test for the property 'PushNotificationPayload'
        }
        /// <summary>
        /// Test the property 'ApplicationState'
        /// </summary>
        [Fact]
        public void ApplicationStateTest()
        {
            // TODO unit test for the property 'ApplicationState'
        }
        /// <summary>
        /// Test the property 'ActionIdentifier'
        /// </summary>
        [Fact]
        public void ActionIdentifierTest()
        {
            // TODO unit test for the property 'ActionIdentifier'
        }
        /// <summary>
        /// Test the property 'PushMessageBehavior'
        /// </summary>
        [Fact]
        public void PushMessageBehaviorTest()
        {
            // TODO unit test for the property 'PushMessageBehavior'
        }

    }

}
