


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing ScreenViewEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScreenViewEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScreenViewEventDataAllOf
        //private ScreenViewEventDataAllOf instance;

        public ScreenViewEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of ScreenViewEventDataAllOf
            //instance = new ScreenViewEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScreenViewEventDataAllOf
        /// </summary>
        [Fact]
        public void ScreenViewEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ScreenViewEventDataAllOf
            //Assert.IsInstanceOfType<ScreenViewEventDataAllOf> (instance, "variable 'instance' is a ScreenViewEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'ScreenName'
        /// </summary>
        [Fact]
        public void ScreenNameTest()
        {
            // TODO unit test for the property 'ScreenName'
        }
        /// <summary>
        /// Test the property 'ActivityType'
        /// </summary>
        [Fact]
        public void ActivityTypeTest()
        {
            // TODO unit test for the property 'ActivityType'
        }
        /// <summary>
        /// Test the property 'CustomFlags'
        /// </summary>
        [Fact]
        public void CustomFlagsTest()
        {
            // TODO unit test for the property 'CustomFlags'
        }

    }

}
