


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing SessionEndEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionEndEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionEndEventDataAllOf
        //private SessionEndEventDataAllOf instance;

        public SessionEndEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of SessionEndEventDataAllOf
            //instance = new SessionEndEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionEndEventDataAllOf
        /// </summary>
        [Fact]
        public void SessionEndEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SessionEndEventDataAllOf
            //Assert.IsInstanceOfType<SessionEndEventDataAllOf> (instance, "variable 'instance' is a SessionEndEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'SessionDurationMs'
        /// </summary>
        [Fact]
        public void SessionDurationMsTest()
        {
            // TODO unit test for the property 'SessionDurationMs'
        }

    }

}
