


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing SessionEndEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionEndEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionEndEvent
        //private SessionEndEvent instance;

        public SessionEndEventTests()
        {
            // TODO uncomment below to create an instance of SessionEndEvent
            //instance = new SessionEndEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionEndEvent
        /// </summary>
        [Fact]
        public void SessionEndEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SessionEndEvent
            //Assert.IsInstanceOfType<SessionEndEvent> (instance, "variable 'instance' is a SessionEndEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
