


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing SessionStartEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionStartEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionStartEventDataAllOf
        //private SessionStartEventDataAllOf instance;

        public SessionStartEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of SessionStartEventDataAllOf
            //instance = new SessionStartEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionStartEventDataAllOf
        /// </summary>
        [Fact]
        public void SessionStartEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SessionStartEventDataAllOf
            //Assert.IsInstanceOfType<SessionStartEventDataAllOf> (instance, "variable 'instance' is a SessionStartEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }

    }

}
