


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing ShoppingCart
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShoppingCartTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShoppingCart
        //private ShoppingCart instance;

        public ShoppingCartTests()
        {
            // TODO uncomment below to create an instance of ShoppingCart
            //instance = new ShoppingCart();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShoppingCart
        /// </summary>
        [Fact]
        public void ShoppingCartInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ShoppingCart
            //Assert.IsInstanceOfType<ShoppingCart> (instance, "variable 'instance' is a ShoppingCart");
        }


        /// <summary>
        /// Test the property 'Products'
        /// </summary>
        [Fact]
        public void ProductsTest()
        {
            // TODO unit test for the property 'Products'
        }

    }

}
