


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing SourceInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SourceInformationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SourceInformation
        //private SourceInformation instance;

        public SourceInformationTests()
        {
            // TODO uncomment below to create an instance of SourceInformation
            //instance = new SourceInformation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SourceInformation
        /// </summary>
        [Fact]
        public void SourceInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SourceInformation
            //Assert.IsInstanceOfType<SourceInformation> (instance, "variable 'instance' is a SourceInformation");
        }


        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'Partner'
        /// </summary>
        [Fact]
        public void PartnerTest()
        {
            // TODO unit test for the property 'Partner'
        }
        /// <summary>
        /// Test the property 'ReplayRequestId'
        /// </summary>
        [Fact]
        public void ReplayRequestIdTest()
        {
            // TODO unit test for the property 'ReplayRequestId'
        }
        /// <summary>
        /// Test the property 'ReplayJobId'
        /// </summary>
        [Fact]
        public void ReplayJobIdTest()
        {
            // TODO unit test for the property 'ReplayJobId'
        }
        /// <summary>
        /// Test the property 'IsHistorical'
        /// </summary>
        [Fact]
        public void IsHistoricalTest()
        {
            // TODO unit test for the property 'IsHistorical'
        }

    }

}
