


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing UserAttributeChangeEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAttributeChangeEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAttributeChangeEvent
        //private UserAttributeChangeEvent instance;

        public UserAttributeChangeEventTests()
        {
            // TODO uncomment below to create an instance of UserAttributeChangeEvent
            //instance = new UserAttributeChangeEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAttributeChangeEvent
        /// </summary>
        [Fact]
        public void UserAttributeChangeEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAttributeChangeEvent
            //Assert.IsInstanceOfType<UserAttributeChangeEvent> (instance, "variable 'instance' is a UserAttributeChangeEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
