


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing UserAttributeChangeEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAttributeChangeEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAttributeChangeEventDataAllOf
        //private UserAttributeChangeEventDataAllOf instance;

        public UserAttributeChangeEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of UserAttributeChangeEventDataAllOf
            //instance = new UserAttributeChangeEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAttributeChangeEventDataAllOf
        /// </summary>
        [Fact]
        public void UserAttributeChangeEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAttributeChangeEventDataAllOf
            //Assert.IsInstanceOfType<UserAttributeChangeEventDataAllOf> (instance, "variable 'instance' is a UserAttributeChangeEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'UserAttributeName'
        /// </summary>
        [Fact]
        public void UserAttributeNameTest()
        {
            // TODO unit test for the property 'UserAttributeName'
        }
        /// <summary>
        /// Test the property 'New'
        /// </summary>
        [Fact]
        public void NewTest()
        {
            // TODO unit test for the property 'New'
        }
        /// <summary>
        /// Test the property 'Old'
        /// </summary>
        [Fact]
        public void OldTest()
        {
            // TODO unit test for the property 'Old'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'IsNewAttribute'
        /// </summary>
        [Fact]
        public void IsNewAttributeTest()
        {
            // TODO unit test for the property 'IsNewAttribute'
        }

    }

}
