


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing UserIdentityChangeEventDataAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserIdentityChangeEventDataAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserIdentityChangeEventDataAllOf
        //private UserIdentityChangeEventDataAllOf instance;

        public UserIdentityChangeEventDataAllOfTests()
        {
            // TODO uncomment below to create an instance of UserIdentityChangeEventDataAllOf
            //instance = new UserIdentityChangeEventDataAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserIdentityChangeEventDataAllOf
        /// </summary>
        [Fact]
        public void UserIdentityChangeEventDataAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserIdentityChangeEventDataAllOf
            //Assert.IsInstanceOfType<UserIdentityChangeEventDataAllOf> (instance, "variable 'instance' is a UserIdentityChangeEventDataAllOf");
        }


        /// <summary>
        /// Test the property 'New'
        /// </summary>
        [Fact]
        public void NewTest()
        {
            // TODO unit test for the property 'New'
        }
        /// <summary>
        /// Test the property 'Old'
        /// </summary>
        [Fact]
        public void OldTest()
        {
            // TODO unit test for the property 'Old'
        }

    }

}
