


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;
using mParticle.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing UserIdentityChangeEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserIdentityChangeEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserIdentityChangeEvent
        //private UserIdentityChangeEvent instance;

        public UserIdentityChangeEventTests()
        {
            // TODO uncomment below to create an instance of UserIdentityChangeEvent
            //instance = new UserIdentityChangeEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserIdentityChangeEvent
        /// </summary>
        [Fact]
        public void UserIdentityChangeEventInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserIdentityChangeEvent
            //Assert.IsInstanceOfType<UserIdentityChangeEvent> (instance, "variable 'instance' is a UserIdentityChangeEvent");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }

    }

}
