


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using mParticle.Api;
using mParticle.Model;
using mParticle.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing UserIdentity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserIdentityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserIdentity
        //private UserIdentity instance;

        public UserIdentityTests()
        {
            // TODO uncomment below to create an instance of UserIdentity
            //instance = new UserIdentity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserIdentity
        /// </summary>
        [Fact]
        public void UserIdentityInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserIdentity
            //Assert.IsInstanceOfType<UserIdentity> (instance, "variable 'instance' is a UserIdentity");
        }


        /// <summary>
        /// Test the property 'IdentityType'
        /// </summary>
        [Fact]
        public void IdentityTypeTest()
        {
            // TODO unit test for the property 'IdentityType'
        }
        /// <summary>
        /// Test the property 'Identity'
        /// </summary>
        [Fact]
        public void IdentityTest()
        {
            // TODO unit test for the property 'Identity'
        }
        /// <summary>
        /// Test the property 'TimestampUnixtimeMs'
        /// </summary>
        [Fact]
        public void TimestampUnixtimeMsTest()
        {
            // TODO unit test for the property 'TimestampUnixtimeMs'
        }
        /// <summary>
        /// Test the property 'CreatedThisBatch'
        /// </summary>
        [Fact]
        public void CreatedThisBatchTest()
        {
            // TODO unit test for the property 'CreatedThisBatch'
        }

    }

}
