

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using mParticle.Sdk.Client;
using mParticle.Sdk.Api;
using mParticle.Sdk.Model;

namespace mParticle.Sdk.Test
{
    /// <summary>
    ///  Class for testing EventsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EventsApiTests : IDisposable
    {
        private EventsApi instance;

        public EventsApiTests()
        {
            instance = new EventsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EventsApi
            //Assert.IsType(typeof(EventsApi), instance, "instance is a EventsApi");
        }

        
        /// <summary>
        /// Test BulkUploadEvents
        /// </summary>
        [Fact]
        public void BulkUploadEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Collection<Batch> batch = null;
            //instance.BulkUploadEvents(batch);
            
        }
        
        /// <summary>
        /// Test UploadEvents
        /// </summary>
        [Fact]
        public void UploadEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Batch batch = null;
            //instance.UploadEvents(batch);
            
        }
        
    }

}
