

using System;
using Xunit;
using mParticle.Api;
using mParticle.Client;
using System.Collections.ObjectModel;
using mParticle.Model;
using System.Collections.Generic;

namespace mParticle.Test
{
    /// <summary>
    ///  Class for testing EventsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MParticleTests : IDisposable
    {

        public MParticleTests()
        {
            MParticle.Start(new Configuration("api_key", "api_secret"));
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EventsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EventsApi
            Assert.IsType<MParticle>(MParticle.Instance);
        }

        
        /// <summary>
        /// Test BulkUploadEvents
        /// </summary>
        [Fact]
        public void BulkUploadEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            Collection<Batch> batch = new Collection<Batch>();
            MParticle.Instance.BulkUploadBatches(batch);
            
        }
        
        /// <summary>
        /// Test UploadEvents
        /// </summary>
        [Fact]
        public void UploadEventsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            Batch batch = new Batch();
            MParticle.Instance.UploadBatch(batch);   
        }
    }
}
