name: Test

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

  security-checks:
    name: "Security Lint Checks"
    uses: mparticle/mparticle-workflows/.github/workflows/security-checks.yml@main
    with:
      base_branch: "master"
